### ISSUE TITLE
Hello, will your project have a database?

### ISSUE THREAD

**Issue by sebastianjnuwu** [KhaledElbahr/chat.io-app#1]
As I follow projects that contain the "socket.io" dependency, I ended up finding your repository, I found your project very interesting because it is simple and easy to understand the code, one thing I missed was the database to store messages and users, do you think about using it?

**Comment by KhaledElbahr** [comment]
### Hi, Yes in the next version of the project.
Thanks for your interest, Yeah, In the next version will have many updates soon including having a database. I will appreciate it if you tell me also about any features you would like to be added in the upcoming versions.
And If you would like to follow me to get a notification for new updates.

**Comment by sebastianjnuwu** [comment]
Ok, I'll follow the next updates and even make some contribution, I'm playing with the code with my friends and studying about the socket.io, Any new feature that may be added I will let you know....
