### ISSUE TITLE
Implementation suggestion in the next updates if you wish....

### ISSUE THREAD

**Issue by sebastianjnuwu** [KhaledElbahr/chat.io-app#2]
Hello, thinking about improving the appearance of the chat I want to show you this model [On here](https://www.bootdey.com/snippets/view/animated-chat-window), it will just need some adjustments to fit, another thing is button to open a popup and send a Gif an example [here](https://troof.nabilridhwan.com/game/lake-sit-must-goes) , Using the giphy API.

![Screenshot_20230120-032454~2](https://user-images.githubusercontent.com/101356556/213631772-9b66fb19-edbf-442d-a919-b60c9c0c91bc.jpg)
![Screenshot_20230120-032511~2](https://user-images.githubusercontent.com/101356556/213632124-389628bd-4751-4e9c-9676-63b0225cc8f3.jpg)

**Comment by sebastianjnuwu** [comment]
I was testing sending images but depending on the size the chat was buggy, in one of my searches the person used Gif, and for the Gif to appear automatically in the chat just interact with the giphy api possible?

**Comment by sebastianjnuwu** [comment]
These are some ideas, the most interesting thing was to improve the design One idea is this template as I said before [here](https://www.bootdey.com/snippets/view/animated-chat-window)

**Comment by KhaledElbahr** [comment]
Hello, hope you do well.
That's great ideas I will put them into consideration for the new version. thank you so much and inform me of more features do you suggest to be added in the chat.
